# Generated by Django 3.2.20 on 2023-08-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0004_auto_20230731_1556"),
    ]

    operations = [
    ]
