# Generated by Django 3.2.20 on 2023-08-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dongtai_common", "0007_auto_20230803_1810"),
    ]

    operations = [
    ]
